// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package router

import (
	"github.com/ckhero/go-common/config"
	"github.com/ckhero/go-common/db"
	"github.com/ckhero/go-common/wx"
	"nine-village-road/internal/repo"
	"nine-village-road/internal/service"
	"nine-village-road/internal/usecase"
)

// Injectors from wire.go:

func newWechatService() (*service.WechatService, func(), error) {
	weixinPay := config.GetWeixinPayCfg()
	client := wx.NewMiniPayClient(weixinPay)
	miniProgram := wx.NewMiniClient()
	weixinRepo := repo.NewWeixinRepo(client, miniProgram)
	database := db.NewDatabase()
	userRedPacketRepo := repo.NewUserRedPacketRepo(database)
	userRepo := repo.NewUserRepo(database)
	redPacketLimitRepo := repo.NewRedPacketLimitRepo(database)
	weixinUsecase := usecase.NewWeixinUsecase(weixinRepo, userRedPacketRepo, userRepo, redPacketLimitRepo)
	wechatService := service.NewWechatService(weixinUsecase)
	return wechatService, func() {
	}, nil
}

func newUserService() (*service.UserService, func(), error) {
	database := db.NewDatabase()
	userRepo := repo.NewUserRepo(database)
	weixinPay := config.GetWeixinPayCfg()
	client := wx.NewMiniPayClient(weixinPay)
	miniProgram := wx.NewMiniClient()
	weixinRepo := repo.NewWeixinRepo(client, miniProgram)
	userRedPacketRepo := repo.NewUserRedPacketRepo(database)
	userUsecase := usecase.NewUserUsecase(userRepo, weixinRepo, userRedPacketRepo)
	redPacketLimitRepo := repo.NewRedPacketLimitRepo(database)
	weixinUsecase := usecase.NewWeixinUsecase(weixinRepo, userRedPacketRepo, userRepo, redPacketLimitRepo)
	userScenicRepo := repo.NewUserScenicRepo(database)
	userScenicUsecase := usecase.NewUserScenicUsecase(userScenicRepo)
	userService := service.NewUserService(userUsecase, weixinUsecase, userScenicUsecase)
	return userService, func() {
	}, nil
}
